[program:django]
command=/usr/bin/python manage.py runserver 0.0.0.0:8080 --insecure
directory=/saas/projects/AnsibleWeb/
stdout_logfile=/saas/projects/AnsibleWeb/logs/django/django_output.log
stdout_logfile_maxbytes=200MB
stderr_logfile=/saas/projects/AnsibleWeb/logs/django/django_error.log
stderr_logfile_maxbytes=200MB
startretries=3
stopasgroup=true
